import json
import dataclasses
from typing import List, Dict, Any
from google import genai
from google.genai import types

@dataclasses.dataclass
class AgentTrace:
    agent_version: str
    steps: List[Dict[str, Any]]
    final_output: str
    total_tokens: int
    latency_seconds: float

@dataclasses.dataclass
class EvalResult:
    winner: str
    score_delta: float
    regression_detected: bool
    reasoning: str
    flagged_issues: List[str]

class DeterministicEvaluator:
    def __init__(self, max_allowed_steps: int = 5):
        self.max_allowed_steps = max_allowed_steps

    def verify_trace(self, trace: AgentTrace) -> List[str]:
        issues = []
        if len(trace.steps) > self.max_allowed_steps:
            issues.append(
                f"Loop regression: Step count {len(trace.steps)} exceeded max limit of {self.max_allowed_steps}"
            )
        for idx, step in enumerate(trace.steps, start=1):
            if "action" not in step:
                issues.append(f"Step {idx}: Missing required 'action' field in trace step.")
            if "query" in step and not isinstance(step["query"], str):
                issues.append(f"Step {idx}: Action query parameter must be a string.")
        return issues

class AgentRegressionJudge:
    def __init__(self, model_name: str = "gemini-2.5-pro"):
        self.client = genai.Client()
        self.model_name = model_name

    def evaluate_pair(self, user_prompt: str, ground_truth: str, 
                      baseline: AgentTrace, candidate: AgentTrace) -> EvalResult:
        
        judge_prompt = f"""USER TASK: {user_prompt}
EXPECTED GROUND TRUTH: {ground_truth}

--- BASELINE EXECUTION TRACE (v{baseline.agent_version}) ---
Steps: {json.dumps(baseline.steps, indent=2)}
Final Output: {baseline.final_output}

--- CANDIDATE EXECUTION TRACE (v{candidate.agent_version}) ---
Steps: {json.dumps(candidate.steps, indent=2)}
Final Output: {candidate.final_output}
"""
        
        # System instructions to enforce the JSON schema response are assumed in production.
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=judge_prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.0,
            )
        )
        data = json.loads(response.text)
        
        return EvalResult(
            winner=data["winner"],
            score_delta=data.get("score_delta", 0.0),
            regression_detected=data.get("regression_detected", False),
            reasoning=data["reasoning"],
            flagged_issues=data.get("flagged_issues", [])
        )

def run_regression_test_suite():
    print("--- Starting Agent Regression Test Suite ---")
    
    user_task = "Find the total revenue generated by active subscribers in August 2026."
    ground_truth = "Total revenue: $142,500.00 from 1,425 active users."
    
    baseline_trace = AgentTrace(
        agent_version="1.0.0",
        steps=[{"step": 1, "action": "sql_query", "query": "SELECT SUM(amount) FROM payments WHERE month = '2026-08' AND status = 'active'"}],
        final_output="Active subscriber revenue for August 2026 was $142,500.00.",
        total_tokens=450,
        latency_seconds=1.2,
    )
    
    candidate_trace = AgentTrace(
        agent_version="1.1.0-rc1",
        steps=[
            {"step": 1, "action": "sql_query", "query": "SELECT * FROM users"},
            {"step": 2, "action": "sql_query", "query": "SELECT * FROM user_subscriptions"},
            {"step": 3, "action": "sql_query", "query": "SELECT SUM(amount) FROM payments"},
        ],
        final_output="The estimated revenue is around $142,500.",
        total_tokens=1850,
        latency_seconds=4.8,
    )
    
    # Layer 1 Eval
    det_eval = DeterministicEvaluator(max_allowed_steps=2)
    det_issues = det_eval.verify_trace(candidate_trace)
    
    if det_issues:
        print(f"[FAIL] Deterministic Gate Issues Detected:")
        for issue in det_issues:
            print(f"  - {issue}")
            
    # Layer 2 Eval
    judge = AgentRegressionJudge()
    eval_result = judge.evaluate_pair(user_task, ground_truth, baseline_trace, candidate_trace)
    
    print(f"\n[EVALUATION REPORT]")
    print(f"Winner: {eval_result.winner}")
    print(f"Score Delta: {eval_result.score_delta}")
    print(f"Regression Detected: {eval_result.regression_detected}")
    print(f"Reasoning: {eval_result.reasoning}")
    
    all_issues = det_issues + eval_result.flagged_issues
    
    # CI/CD Gate Assertions
    assert not eval_result.regression_detected, f"Pipeline Blocked! Regressions: {all_issues}"
    assert eval_result.score_delta >= -0.3, f"Pipeline Blocked! Quality score dropped by {eval_result.score_delta}"

if __name__ == "__main__":
    run_regression_test_suite()